phraseapp:
  project_id: 2efd2a34f3dfc629fefeb1e2dc117547
  push:
    sources:
    - file: ./locales/de.json
      params:
        file_format: json
  pull:
    targets:
    - file: ./locales/<locale_name>.json
      params:
        file_format: json
