phraseapp:
  access_token: "d0792459e43ff0559711076748f222bf76b7be5cafc5b451424b1480c930a9de"
  project_id: "d74df7053a810351aad68f06632fe95d"
  push:
    sources:
    - file: ./locales/en-simple.yml
      params:
        file_format: yml
        tags: simple
    - file: ./locales/en-advanced.yml
      params:
        file_format: yml
        tags: "advanced, custom"
  pull:
    targets:
    - file: ./locales/<locale_name>-simple.yml
      params:
        file_format: yml
        tags: simple
    - file: ./locales/<locale_name>-advanced.yml
      params:
        file_format: yml
        tags: "advanced, custom"
